Add "boot.localfs" to Required-Stop
Fix build in SUSE:
---------------------------- 8< ------------------------------------------------
E: File `kdump' does require services for start but nothing for stop, if
   intended use `$null'!
ERROR: found one or more broken init or boot scripts, please fix them.
       For more information about LSB headers please read the manual
       page of of insserv by executing the command `man 8 insserv'.
       If you don't understand this, mailto=werner@suse.de
---------------------------- >8 ------------------------------------------------